name: biller_mobile
description: "A Flutter mobile app for Biller-V2 expense tracking system"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and Material Design
  material_color_utilities: ^0.8.0
  cupertino_icons: ^1.0.6
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  
  # Google Sign In
  google_sign_in: ^6.1.6
  
  # Image handling and camera
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  image: ^4.1.3
  
  # Charts and analytics
  fl_chart: ^0.64.0
  syncfusion_flutter_charts: ^23.2.7
  
  # State management
  provider: ^6.1.1
  
  # HTTP and networking
  http: ^1.1.0
  
  # Utilities
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  
  # Loading and animations
  shimmer: ^3.0.0
  lottie: ^2.7.0
  
  # PDF and file handling
  path: ^1.8.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700